### ISSUE TITLE
SvgPathSegList is now deprecated in Chrome version 48

### ISSUE THREAD

**Issue by nimshory** [kovacsv/JSModeler#15]
This causes SvgToModel to break.
There is a polyfill available at: https://github.com/progers/pathseg

**Comment by kovacsv** [comment]
Thanks for the report. Including the mentioned polyfill it seems working for me, but it would great to find a solution without polyfills.

**Comment by kovacsv** [comment]
The mentioned polyfill is now available in the build/lib folder.
