### ISSUE TITLE
Prism Generator

### ISSUE THREAD

**Issue by mhemrg** [kovacsv/JSModeler#16]
Hi,
Is there any way to use Prism Generator in our project (like in demo)?

**Comment by kovacsv** [comment]
Hi,

Of course you can use anything in your project, including the prism generator, and the UI. If you would be more specific, maybe I could give you some tips.

Viktor

**Comment by mhemrg** [comment]
Yes, I'm interested in to listen your tips.
But I'm new in HTML5 Canvas!

**Comment by kovacsv** [comment]
Ok, so what would you like to do?

**Comment by mhemrg** [comment]
I'm going to create a pad for my user so they can draw a shape on it (Like pen tool in Photoshop or your prism generator in demo page). After that, I will create a 3D room from that shape.

**Comment by indranyeve** [comment]
hello, I'd like to know if it's posible to sculp a 3D object from zero, I mean starding from nothing and truning into a cup, a bottle, a glass of wine, can I do that with this pluging or this olny work for cubes and basic forms???

**Comment by kovacsv** [comment]
Hi! Sculpting is not possible, but JSModeler contains importer for 3ds, obj and stl files.

**Comment by kovacsv** [comment]
Dear mherg! Please take a look at the sandbox folder. There you can find a polygon editor, and examples on using the framework. If you created the polygon with any tool, I can help you to generate a prism from the points of the polygon.

**Comment by kovacsv** [comment]
I have created a fiddle, which generates a room from a polygon:
http://jsfiddle.net/Lnye1t1x/1/

**Comment by mhemrg** [comment]
Yes!
Thanks a lot for this snippet.
