### ISSUE TITLE
GenerateWireBody rendering broken

### ISSUE THREAD

**Issue by shiruken1** [kovacsv/JSModeler#22]
Hello again!

Just to give you a head's up, as of Firefox v50.1.0 and Chrome v55.0.2883.87, GenerateWireBody is having rendering problems. I would assume something in their latest implementation of WebGL changed, so as to impact the Line shader script.

When I run [your fiddle](http://jsfiddle.net/65gpb5o8/4/), I get [this output](http://www.awesomescreenshot.com/image/2134502/11950ebc0b4f16c6d88b8e9bb5bb812d)

All the best, and thanks in advance for any help!

**Comment by shiruken1** [comment]
sandbox/linesandpoints.html illustrates this better.

**Comment by kovacsv** [comment]
Hello,

It is strange, it works for me, What operating system do you use?

I crated the same example with the internal, and the three.js based viewer. Does it work for you?
http://jsfiddle.net/yunq4tys/1/

Viktor

**Comment by shiruken1** [comment]
Nope. I get the same thing like in sandbox/linesandpoints.html:

http://www.awesomescreenshot.com/image/2136715/26d713d9ddd01a6e3e2a9995c327aa0a

I'm running Ubuntu 16.04 on both my desktop and laptop, as well as a friend's desktop, all showing the same glitch.

Thank you so much for the help!

**Comment by kovacsv** [comment]
It seems that the problem appears only with the internal viewer. As a workaround you can use the three.js based viewer. It has the same functionality but uses three.js to show models.

**Comment by shiruken1** [comment]
FWIW, Win10 running Chrome55.0.2883.87 and FF51.0.1 renders grids perfectly, so your initial hunch of it being an OS issue seems to be correct.

**Comment by shiruken1** [comment]
I've been able to fix this issue by initializing the diffuseComponent to vec3(0.0) in the point and line fragment shader script. Let me know if that works on other OS/browsers.

**Comment by kovacsv** [comment]
Good catch, thank you very much. It works on windows, too. I commited the change to development branch!
