### ISSUE TITLE
How to create FirstPersonControls?

### ISSUE THREAD

**Issue by thientu995** [kovacsv/JSModeler#38]
How do I create a new camera in "First Person" mode? I made a move with the keyboard "W, A, S, D", but I'm having problems: the character can look to the left, right, up & down, however if we imagine the head of the character it can't be tilted
Looking forward to help, thanks in advance!

**Comment by thientu995** [comment]
Thank you for taking the time to respond to my question. I solved the problem I set out :)

**Comment by thientu995** [comment]
Tôi đang gặp phải vấn đề khi đọc file ifc của 1 model 3d bằng jsmodeler. Bạn có thể giúp tôi không?
Xin cảm ơn

**Comment by thientu995** [comment]
I'm having problems reading the ifc file of a 3d model with jsmodeler. Can you help me?
Thank you

**Comment by kovacsv** [comment]
How can I help you with IFC file reading? JSModeler is currently not capable to read IFC files, and it is a pretty hard task, because IFC usually doesn't contain the BRep model, you have to build it up from primitives.

**Comment by thientu995** [comment]
Now is there a way to read other formats besides support .3ds, .obj and .stl with JSModeler like THREE.JS https://github.com/mrdoob/three.js/tree/master/examples/js/loaders . Because, it's different usage of THREE JS?

**Comment by kovacsv** [comment]
No, currently only these file formats are supported.
