### ISSUE TITLE
I want to rotate the loaded model 

### ISSUE THREAD

**Issue by flamehazw** [kovacsv/JSModeler#39]
I like to apply rotation in the 3d model but I cannot set it up correctly. I checked the documentation but didn't get the object rotation. I will update when it gets working anyway.
Thanks

**Comment by kovacsv** [comment]
I'm not sure how can I help you with this. What is the question?

**Comment by flamehazw** [comment]
I got the answer from this https://github.com/kovacsv/JSModeler/issues/30 
thanks
