### ISSUE TITLE
Canvas Background Attributes

### ISSUE THREAD

**Issue by TenEightyOne** [kovacsv/JSModeler#42]
I'd like to use JSModeler within a web page but I'd like to change the background attributes to another colour. Is there a way of plugging this into the initial call, and if not how would it be done?

Many thanks for your work on this - it's fantastic!

**Comment by kovacsv** [comment]
Hi,

It's not possible to set it in the initial call, but you can modify it after the Start call:
```js
var viewer = new JSM.ThreeViewer ();
viewer.Start (document.getElementById ('example'), viewerSettings);
viewer.renderer.setClearColor (new THREE.Color (0xff0000));
```
Hop it helps!

**Comment by TenEightyOne** [comment]
Thank you very much :)
